email=input("Enter your Email:")
nm=input("Enter your Name:")
mob=int(input("Enter your Mobile_no.:"))
roll=int(input("Enter your Roll_no.:"))
print("\n Email:",email)
print("\n Name:",nm)
print("\n Mobile_no.:",mob)
print("\n Roll_no.:",roll)
